name: "Terraform-Plan"

on:
  push:
    branches:
      - "*"
defaults:
  run:
    shell: bash
    working-directory: src/main


jobs:
  terraform:
    name: "Deploy-Development-Environment"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.8


      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: |
          ./terraform.sh init prod

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: |
          ./terraform.sh plan prod
        continue-on-error: true