name: "Terraform-Apply"

on:
  push:
    branches:
      - main
    paths:
      - src/main
      - '.github/workflows/*.yml'

env:
 AWS_REGION: eu-central-1
 IAM_ROLE: arn:aws:iam::794703684555:role/GitHubActionIACRole

defaults:
  run:
    shell: bash
    working-directory: src/main

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  terraform:
    name: "Deploy-Development-Environment"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Read terraform version 
        id: read-version
        run: |
          echo "TERRAFORM_VERSION=`cat ../.terraform-version`"
          echo "TERRAFORM_VERSION=`cat ../.terraform-version`" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init
        id: init
        run: |
          ./terraform.sh init prod

      - name: Terraform Apply
        id: apply
        run: |
          ./terraform.sh apply prod -auto-approve
        continue-on-error: true